### ISSUE TITLE
Yarn error - package.json contains no version

### ISSUE THREAD

**Issue by bitjoo** [components/handlebars.js#23] opened 2017-11-21 12:02 UTC
When I want to install this dependency with yarn, it logs an error "couldn't find a version". Please provide a valid package.json.

**Comment by nknapp** [comment] 2017-11-22 16:22
What is your exact dependency entry? When you use handlebars with yarn, you should not end up in this repository. At least I thought. Doesn't yarn use an npm-mirror? That should be wycats/handlebarsjs then.

**Comment by hsalokor** [comment] 2017-11-27 11:32
This happens at least when moving from Bower to Yarn using `bower-away`: https://github.com/sheerun/bower-away

This is entry that `bower-away` generates:

`"@bower_components/handlebars": "components/handlebars.js#^4.0.11",`

Since there is no `version` field in `package.json`, yarn gets confused when generating `yarn.lock` and generates entry with no dependencies and no version.

Unfortunately at least in our case the `wycats/handlebars.js` is not a drop-in replacement, but seems to require reworking a fair amount of require-mappings.

**Comment by hsalokor** [comment] 2017-11-27 11:41
Here's a reproducible test case:

minimal *package.json*

```
{
  "name": "yarn-install-failure",
  "version": "1.0.0",
  "dependencies": {
    "@bower_components/handlebars": "components/handlebars.js#^4.0.11"
  },
  "license": "UNLICENCED"
}
```

Steps to reproduce:

First run

```
$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1.95s.
```

Second run (that will fail)

```
$ yarn install
yarn install v1.3.2
warning package.json: No license field
warning yarn-install-failure@1.0.0: No license field
[1/4] 🔍  Resolving packages...
error Package "@bower_components/handlebars@" doesn't have a "version".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Resulting `yarn.lock`

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@bower_components/handlebars@components/handlebars.js#^4.0.11":
  version ""
  resolved "https://codeload.github.com/components/handlebars.js/tar.gz/1e6b16fdbcc85e653a0bceb31902676b390c9e01"
```

**Comment by bitjoo** [comment] 2017-11-27 14:14
Thank you @hsalokor for your detailed error description. Until now I hadn't time to respond.

**Comment by hsalokor** [comment] 2017-11-27 14:52
One thing came to my mind: Github probably caches the released tar.gz and zip files, so some kind of release bump is probably needed in order to get the package.json fix out into the wild.

**Comment by hsalokor** [comment] 2017-11-27 15:17
Thanks for access 👋 

I did a bit of nasty by moving the git tag forward couple of commits without bumping the version, and making Github regenerate the release package. This *should* be quite safe operation.

Updating to yarn-friendly latest version requires purging yarn cache with `yarn cache clean` command. I've now verified that the current `4.0.11` version is in fact yarn compatible.

**Comment by hsalokor** [comment] 2017-11-27 15:17
I'll close the issue for now - please report if you encounter any unexpected issues.

**Closed by hsalokor** 2017-11-27 15:17 UTC

**Comment by nknapp** [comment] 2017-11-27 20:00
Is there anything to do in [wycats/handlebars.js](https://github.com/wycats/handlebars.js). I fear that his is going to break on the next Handlebars release, or do I have to update the package.json manually?

**Comment by hsalokor** [comment] 2017-11-27 20:22
It is a good question. I think manual management of the version numbers is error prone, but only thing I can think of is automation on shim-release side.

Any ideas are welcome.

**Comment by hsalokor** [comment] 2017-11-27 20:23
Of course, maintainers can handle this, but it is a bit more work for each release.

**Comment by hsalokor** [comment] 2017-11-27 20:42
Ah - to clarify: this does not affect the upstream wycats/habdlebars.js repository. The yarn issue is purely issue with the shim repository and the package.json here (I hope I understood the question correctly?)

**Comment by nknapp** [comment] 2017-11-27 21:20
New releases in the `components/handlebars.js`-repository are created using the command `yo release:publish components dist/components`, executed in `wycats/handlebars.js`. This command does not push the `package.json`. I'm not sure what it takes to fix that, but I fear this would be a new feature in `generator-release`.

**Comment by hsalokor** [comment] 2017-11-27 21:23
Hmm. That sounds ominous. I need to take a look at that tomorrow. Good thing is that there is automation.

**Comment by nknapp** [comment] 2017-11-27 21:26
https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md#releasing

**Comment by hsalokor** [comment] 2017-11-28 14:48
@nknapp it looks to me like adding current `package.json` here to upstream project (wycats/handlebars.js) `components` directory should do the trick.

I took a look at the yeoman `release-generator` and it looks like those files act like templates, and the release plugin updates the version fields there.

I haven't been able to set up a reasonable test environment, so this is currently only a strong hunch.

**Comment by nknapp** [comment] 2017-11-28 21:06
I'll try that for the next release. If it does not work, we have to force push tags again.

**Comment by hsalokor** [comment] 2017-11-29 08:27
Sounds like a plan +1
